language: go
go: 1.10.x
sudo: required
env:
- BUNDLE_BUILD_NUM=TRAVIS_BUILD_NUMBER
services:
- docker
before_install:
- docker pull karalabe/xgo-latest
- sudo add-apt-repository ppa:webkit-team/ppa
- sudo apt-get update
- sudo apt-get install -y libwebkit2gtk-4.0-37 libwebkit2gtk-4.0-dev
install:
- go get github.com/karalabe/xgo
- go get -u github.com/dags-/bundler
script:
- bundler
deploy:
  provider: releases
  api_key: '$GITHUB_AUTH'
  file: 
  - "builds/darwin/*.zip"
  - "builds/linux/*.AppImage"
  - "builds/windows/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
