language: go
go: 1.10.x
sudo: required
services:
 - docker
before_install:
 - docker pull karalabe/xgo-latest
install:
 - go get github.com/karalabe/xgo
 - go get -u github.com/dags-/bundler
script:
 - bundler
deploy:
  provider: releases
  api_key: '$GITHUB_AUTH'
  file: "builds/**/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
